name: Sync with AWS' S3

on: 
  push: 
    branches: 
      - main # i.e., pushing onto this branch will trigger this workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      
      # We must setup Node in the Github Actions because our website 
      # is a React app created using Vite, which is built and managed 
      # by Node.js. Installing Node provides access to NPM, which is 
      # used for managing dependencies of the site. This allows us to 
      # install the necessary dependencies when running a build on the site. 
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with: 
          node-version: '20' # The node version we'll use for building the app

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Sync with S3
        run: aws s3 sync dist/ s3://naifsitebucket
